;;; init.el --- Minimal Emacs setup for coding agents -*- lexical-binding: t; -*-

(require 'package)
(require 'subr-x)

(setq package-archives
      '(("gnu"    . "https://elpa.gnu.org/packages/")
        ("nongnu" . "https://elpa.nongnu.org/nongnu/")
        ("melpa"  . "https://melpa.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(require 'use-package)

(setq custom-file (locate-user-emacs-file "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file nil 'nomessage))

;;;; Shared ALMA devcontainer bridge

(defconst my/devcontainer-bin-dir
  (locate-user-emacs-file "bin/")
  "Directory for helper executables generated by this config.")

(defun my/write-executable (name contents)
  "Create executable NAME with CONTENTS under `my/devcontainer-bin-dir'."
  (make-directory my/devcontainer-bin-dir t)
  (let ((path (expand-file-name name my/devcontainer-bin-dir)))
    (with-temp-file path
      (insert contents))
    (set-file-modes path #o755)
    path))

(defun my/devcontainer-wrapper (program)
  "Return a wrapper that runs PROGRAM in the shared ALMA devcontainer.

Projects under $ALMA_PROJECTS share one devcontainer.  The devcontainer
definition is rooted at $ALMA_PROJECTS/repos/alma, while the actual command
keeps the current project directory because the whole ALMA_PROJECTS tree is
mounted at the same absolute path inside the container."
  (my/write-executable
   (format "%s-emacs" program)
   (format
    "#!/bin/sh
set -eu

host_cwd=$PWD
alma_projects=${ALMA_PROJECTS:-}

case \"$host_cwd/\" in
  \"${alma_projects}/\"*)
    if [ -z \"$alma_projects\" ]; then
      exec %s \"$@\"
    fi

    workspace=\"$alma_projects/repos/alma\"

    if ! command -v devcontainer >/dev/null 2>&1; then
      echo \"devcontainer CLI is required on the host for ALMA projects\" >&2
      exit 127
    fi

    if [ ! -e \"$workspace/.devcontainer/devcontainer.json\" ] &&
       [ ! -e \"$workspace/.devcontainer.json\" ]; then
      echo \"ALMA devcontainer definition not found under $workspace\" >&2
      exit 1
    fi

    exec devcontainer exec --workspace-folder \"$workspace\" \
      sh -lc 'cd \"$1\"; shift; exec \"$@\"' sh \"$host_cwd\" %s \"$@\"
    ;;
esac

exec %s \"$@\"
"
    program program program)))

(defconst my/codex-program (my/devcontainer-wrapper "codex"))
(defconst my/claude-program (my/devcontainer-wrapper "claude"))

;; Git.
(use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))

;; Shared pure-Elisp terminal backend.
(use-package eat
  :ensure t)

;; OpenAI Codex.
(use-package codex
  :vc (:url "https://github.com/benthamite/codex" :rev :newest)
  :after eat
  :custom
  (codex-program my/codex-program)
  (codex-terminal-backend 'app-server)
  :bind-keymap
  ("C-c x" . codex-command-map))

;; Claude Code.
(use-package claude-code-ide
  :vc (:url "https://github.com/manzaltu/claude-code-ide.el" :rev :newest)
  :after eat
  :custom
  (claude-code-ide-cli-path my/claude-program)
  (claude-code-ide-terminal-backend 'eat)
  :bind
  ("C-c C-'" . claude-code-ide-menu)
  :config
  (claude-code-ide-emacs-tools-setup))

(provide 'init)
;;; init.el ends here
