;;; init.el --- Minimal Emacs setup for coding agents -*- lexical-binding: t; -*-

(require 'package)
(require 'project)
(require 'subr-x)

(setq package-archives
      '(("gnu"    . "https://elpa.gnu.org/packages/")
        ("nongnu" . "https://elpa.nongnu.org/nongnu/")
        ("melpa"  . "https://melpa.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(require 'use-package)

(setq custom-file (locate-user-emacs-file "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file nil 'nomessage))

;;;; ALMA devcontainer bridge

(defconst my/devcontainer-bin-dir
  (locate-user-emacs-file "bin/")
  "Directory for helper executables generated by this config.")

(defconst my/alma-instance-map-file
  (locate-user-emacs-file "alma-instances")
  "Local mapping from project roots to extra ALMA devcontainer instances.")

(defun my/write-executable (name contents)
  "Create executable NAME with CONTENTS under `my/devcontainer-bin-dir'."
  (make-directory my/devcontainer-bin-dir t)
  (let ((path (expand-file-name name my/devcontainer-bin-dir)))
    (with-temp-file path
      (insert contents))
    (set-file-modes path #o755)
    path))

(defun my/alma-project-root ()
  "Return the current project root as an absolute directory name."
  (when-let ((project (project-current nil)))
    (directory-file-name (expand-file-name (project-root project)))))

(defun my/alma-read-instance-map ()
  "Read `my/alma-instance-map-file' as an alist of (ROOT . INSTANCE)."
  (when (file-readable-p my/alma-instance-map-file)
    (with-temp-buffer
      (insert-file-contents my/alma-instance-map-file)
      (let (result)
        (dolist (line (split-string (buffer-string) "\n" t))
          (pcase (split-string line "\t")
            (`(,root ,instance)
             (push (cons root instance) result))))
        (nreverse result)))))

(defun my/alma-write-instance-map (entries)
  "Write project-to-instance ENTRIES to `my/alma-instance-map-file'."
  (with-temp-file my/alma-instance-map-file
    (dolist (entry entries)
      (insert (car entry) "\t" (cdr entry) "\n"))))

(defun my/alma-use-instance (instance)
  "Bind the current project to extra ALMA devcontainer INSTANCE.

The instance is started immediately. Codex and Claude wrappers then discover
the mapping from the current working directory."
  (interactive
   (let* ((root (or (my/alma-project-root)
                    (user-error "Current buffer is not in a project")))
          (default (file-name-nondirectory root)))
     (list (read-string "ALMA instance: " default))))
  (let* ((root (or (my/alma-project-root)
                   (user-error "Current buffer is not in a project")))
         (entries (my/alma-read-instance-map)))
    (setq entries (cons (cons root instance)
                        (assoc-delete-all root entries)))
    (my/alma-write-instance-map entries)
    (let ((buffer (get-buffer-create "*alma-dev-instance*")))
      (unless (zerop
               (call-process "alma-dev-instance" nil buffer t "start" instance))
        (pop-to-buffer buffer)
        (user-error "Failed to start ALMA instance %s" instance)))
    (message "%s -> alma-dev-%s" root instance)))

(defun my/alma-clear-instance ()
  "Remove the extra-instance binding for the current project."
  (interactive)
  (let* ((root (or (my/alma-project-root)
                   (user-error "Current buffer is not in a project")))
         (entries (assoc-delete-all root (my/alma-read-instance-map))))
    (my/alma-write-instance-map entries)
    (message "%s now uses the canonical VS Code devcontainer" root)))

(defun my/alma-show-instance ()
  "Show which ALMA devcontainer instance the current project uses."
  (interactive)
  (let* ((root (or (my/alma-project-root)
                   (user-error "Current buffer is not in a project")))
         (instance (cdr (assoc root (my/alma-read-instance-map)))))
    (message "%s -> %s"
             root
             (if instance
                 (format "alma-dev-%s" instance)
               "canonical alma-dev"))))

(defun my/devcontainer-wrapper (program)
  "Return a wrapper that runs PROGRAM in the appropriate ALMA devcontainer.

Projects without an explicit local mapping use the canonical Dev Containers
instance managed by VS Code. A project mapped by `my/alma-use-instance' uses
alma-dev-instance instead."
  (my/write-executable
   (format "%s-emacs" program)
   (format
    "#!/bin/sh
set -eu

host_cwd=$PWD
alma_projects=${ALMA_PROJECTS:-}
map_file=%s

case \"$host_cwd/\" in
  \"${alma_projects}/\"*)
    if [ -z \"$alma_projects\" ]; then
      exec %s \"$@\"
    fi

    instance=
    if [ -r \"$map_file\" ]; then
      instance=$(awk -F '\\t' -v cwd=\"$host_cwd\" '
        {
          root=$1
          if (cwd == root || index(cwd, root \"/\") == 1) {
            if (length(root) > best) {
              best=length(root)
              found=$2
            }
          }
        }
        END { print found }
      ' \"$map_file\")
    fi

    if [ -n \"$instance\" ]; then
      if ! command -v alma-dev-instance >/dev/null 2>&1; then
        echo \"alma-dev-instance is required on the host\" >&2
        exit 127
      fi
      alma-dev-instance start \"$instance\" >/dev/null
      exec alma-dev-instance exec \"$instance\" %s \"$@\"
    fi

    workspace=\"$alma_projects/repos/alma\"

    if ! command -v devcontainer >/dev/null 2>&1; then
      echo \"devcontainer CLI is required on the host for the canonical ALMA environment\" >&2
      exit 127
    fi

    exec devcontainer exec --workspace-folder \"$workspace\" \
      sh -lc 'cd \"$1\"; shift; exec \"$@\"' sh \"$host_cwd\" %s \"$@\"
    ;;
esac

exec %s \"$@\"
"
    (shell-quote-argument my/alma-instance-map-file)
    program program program program)))

(defconst my/codex-program (my/devcontainer-wrapper "codex"))
(defconst my/claude-program (my/devcontainer-wrapper "claude"))

;; Git remains host-native so commit signing and credentials keep using the host setup.
(use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))

(use-package eat
  :ensure t)

(use-package codex
  :vc (:url "https://github.com/benthamite/codex" :rev :newest)
  :after eat
  :custom
  (codex-program my/codex-program)
  (codex-terminal-backend 'app-server)
  :bind-keymap
  ("C-c x" . codex-command-map))

(use-package claude-code-ide
  :vc (:url "https://github.com/manzaltu/claude-code-ide.el" :rev :newest)
  :after eat
  :custom
  (claude-code-ide-cli-path my/claude-program)
  (claude-code-ide-terminal-backend 'eat)
  :bind
  ("C-c C-'" . claude-code-ide-menu)
  :config
  (claude-code-ide-emacs-tools-setup))

(provide 'init)
;;; init.el ends here
