;;; init.el --- Minimal Emacs setup for coding agents -*- lexical-binding: t; -*-

;; This configuration intentionally starts small.  The first milestone is a
;; comfortable project/Git workflow with Codex and Claude Code inside Emacs.

(require 'package)
(require 'subr-x)

(setq package-archives
      '(("gnu"    . "https://elpa.gnu.org/packages/")
        ("nongnu" . "https://elpa.nongnu.org/nongnu/")
        ("melpa"  . "https://melpa.org/packages/")))

(package-initialize)

;; Needed only on a fresh installation (or after deleting package metadata).
(unless package-archive-contents
  (package-refresh-contents))

(require 'use-package)

;; Keep Customize-generated settings out of init.el.
(setq custom-file (locate-user-emacs-file "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file nil 'nomessage))

;;;; Dev container bridge

(defconst my/devcontainer-bin-dir
  (locate-user-emacs-file "bin/")
  "Directory for small helper executables generated by this config.")

(defun my/write-executable (name contents)
  "Create executable NAME with CONTENTS under `my/devcontainer-bin-dir'."
  (make-directory my/devcontainer-bin-dir t)
  (let ((path (expand-file-name name my/devcontainer-bin-dir)))
    (with-temp-file path
      (insert contents))
    (set-file-modes path #o755)
    path))

(defun my/devcontainer-wrapper (program)
  "Return a wrapper path that runs PROGRAM in a devcontainer when available."
  (my/write-executable
   (format "%s-emacs" program)
   (format
    "#!/bin/sh
set -eu

workspace=\"$PWD\"

if [ -f \"$workspace/.devcontainer/devcontainer.json\" ] || [ -f \"$workspace/.devcontainer.json\" ]; then
  if ! command -v devcontainer >/dev/null 2>&1; then
    echo \"devcontainer CLI is required on the host for this project\" >&2
    exit 127
  fi
  exec devcontainer exec --workspace-folder \"$workspace\" %s \"$@\"
fi

exec %s \"$@\"
"
    program program)))

(defconst my/codex-program (my/devcontainer-wrapper "codex"))
(defconst my/claude-program (my/devcontainer-wrapper "claude"))

;; Manage project devcontainers from Emacs and automatically route
;; `compile' commands through `devcontainer exec'.
(use-package devcontainer
  :ensure t)

;; Git.
(use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))

;; Shared pure-Elisp terminal backend.
(use-package eat
  :ensure t)

;; OpenAI Codex.
;;
;; C-c x     Codex command map
;; M-x codex Start a Codex session for the current project
(use-package codex
  :vc (:url "https://github.com/benthamite/codex" :rev :newest)
  :after eat
  :custom
  (codex-program my/codex-program)
  (codex-terminal-backend 'app-server)
  :bind-keymap
  ("C-c x" . codex-command-map))

;; Claude Code.
;;
;; C-c C-'                 Claude Code transient menu
;; M-x claude-code-ide     Start Claude Code for the current project
;;
;; The MCP tools expose Emacs project/xref/imenu/tree-sitter information to
;; Claude Code, which is the main reason we use the IDE integration.
(use-package claude-code-ide
  :vc (:url "https://github.com/manzaltu/claude-code-ide.el" :rev :newest)
  :after eat
  :custom
  (claude-code-ide-cli-path my/claude-program)
  (claude-code-ide-terminal-backend 'eat)
  :bind
  ("C-c C-'" . claude-code-ide-menu)
  :config
  (claude-code-ide-emacs-tools-setup))

(provide 'init)
;;; init.el ends here
